# Adds namespace to all resources.
namespace: openshift-redhat-marketplace
# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: redhat-marketplace-
# Labels to add to all resources and selectors.
commonLabels:
  redhat.marketplace.com/name: redhat-marketplace-operator
  app.kubernetes.io/managed-by: OLM
  app.kubernetes.io/instance: default
commonAnnotations:
  productID: 068a62892a1e4db39641342e592daa25
  productMetric: FREE
  productName: IBM Cloud Platform Common Services
resources:
  - ../crd
  - ../rbac
  - ../manager
  - ../webhook-openshift
  - ../prometheus
  - ../samples
  - ../scorecard

patchesStrategicMerge:
  - manager_auth_proxy_patch.yaml
  - manager_webhook_patch.yaml

configurations:
  - kustomizeconfig.yaml
vars:
  - name: SERVICE_NAME
    objref:
      kind: Service
      version: v1
      name: controller-manager-service
