apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    productID: 068a62892a1e4db39641342e592daa25
    productMetric: FREE
    productName: IBM Cloud Platform Common Services
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: OLM
    redhat.marketplace.com/name: redhat-marketplace-operator
  name: redhat-marketplace-prometheus-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redhat-marketplace-prometheus-operator
subjects:
- kind: ServiceAccount
  name: redhat-marketplace-prometheus-operator
  namespace: openshift-redhat-marketplace
