apiVersion: v1
kind: Service
metadata:
  annotations:
    productID: 068a62892a1e4db39641342e592daa25
    productMetric: FREE
    productName: IBM Cloud Platform Common Services
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: OLM
    control-plane: controller-manager
    redhat.marketplace.com/name: redhat-marketplace-operator
  name: redhat-marketplace-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: OLM
    control-plane: controller-manager
    redhat.marketplace.com/name: redhat-marketplace-operator
status:
  loadBalancer: {}
