apiVersion: v1
kind: Service
metadata:
  annotations:
    productID: 068a62892a1e4db39641342e592daa25
    productMetric: FREE
    productName: IBM Cloud Platform Common Services
    service.beta.openshift.io/serving-cert-secret-name: redhat-marketplace-controller-manager-service
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: OLM
    redhat.marketplace.com/name: redhat-marketplace-operator
  name: redhat-marketplace-controller-manager-service
spec:
  ports:
  - port: 9443
    targetPort: 9443
  selector:
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: OLM
    control-plane: controller-manager
    redhat.marketplace.com/name: redhat-marketplace-operator
status:
  loadBalancer: {}
